/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StrategiesIndexRouteImport } from './routes/strategies.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as UnfollowSuccessRouteImport } from './routes/unfollow.success'
import { Route as UnfollowLoadingRouteImport } from './routes/unfollow.loading'
import { Route as UnfollowInformationRouteImport } from './routes/unfollow.information'
import { Route as UnfollowFailedRouteImport } from './routes/unfollow.failed'
import { Route as UnfollowConfirmationRouteImport } from './routes/unfollow.confirmation'
import { Route as StrategiesUsernameRouteImport } from './routes/strategies.$username'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as PcxfxRegistrationRouteImport } from './routes/pcxfx.registration'
import { Route as PcxfxLoginRouteImport } from './routes/pcxfx.login'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as DashboardStrategiesRouteImport } from './routes/dashboard.strategies'
import { Route as DashboardSavedStrategiesRouteImport } from './routes/dashboard.saved-strategies'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardNotConnectedRouteImport } from './routes/dashboard.not-connected'
import { Route as DashboardNeedVerifyRouteImport } from './routes/dashboard.need-verify'
import { Route as DashboardNeedFollowingRouteImport } from './routes/dashboard.need-following'
import { Route as DashboardLearnRouteImport } from './routes/dashboard.learn'
import { Route as DashboardFollowedRouteImport } from './routes/dashboard.followed'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as StrategiesStrategyIdStepRouteImport } from './routes/strategies.$strategyId.$step'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const UnfollowSuccessRoute = UnfollowSuccessRouteImport.update({
  id: '/unfollow/success',
  path: '/unfollow/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UnfollowLoadingRoute = UnfollowLoadingRouteImport.update({
  id: '/unfollow/loading',
  path: '/unfollow/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const UnfollowInformationRoute = UnfollowInformationRouteImport.update({
  id: '/unfollow/information',
  path: '/unfollow/information',
  getParentRoute: () => rootRouteImport,
} as any)
const UnfollowFailedRoute = UnfollowFailedRouteImport.update({
  id: '/unfollow/failed',
  path: '/unfollow/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const UnfollowConfirmationRoute = UnfollowConfirmationRouteImport.update({
  id: '/unfollow/confirmation',
  path: '/unfollow/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesUsernameRoute = StrategiesUsernameRouteImport.update({
  id: '/strategies/$username',
  path: '/strategies/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => SitemapRoute,
} as any)
const PcxfxRegistrationRoute = PcxfxRegistrationRouteImport.update({
  id: '/pcxfx/registration',
  path: '/pcxfx/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PcxfxLoginRoute = PcxfxLoginRouteImport.update({
  id: '/pcxfx/login',
  path: '/pcxfx/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStrategiesRoute = DashboardStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedStrategiesRoute =
  DashboardSavedStrategiesRouteImport.update({
    id: '/saved-strategies',
    path: '/saved-strategies',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotConnectedRoute = DashboardNotConnectedRouteImport.update({
  id: '/not-connected',
  path: '/not-connected',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNeedVerifyRoute = DashboardNeedVerifyRouteImport.update({
  id: '/need-verify',
  path: '/need-verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNeedFollowingRoute = DashboardNeedFollowingRouteImport.update({
  id: '/need-following',
  path: '/need-following',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLearnRoute = DashboardLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFollowedRoute = DashboardFollowedRouteImport.update({
  id: '/followed',
  path: '/followed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const StrategiesStrategyIdStepRoute =
  StrategiesStrategyIdStepRouteImport.update({
    id: '/strategies/$strategyId/$step',
    path: '/strategies/$strategyId/$step',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/followed': typeof DashboardFollowedRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/need-following': typeof DashboardNeedFollowingRoute
  '/dashboard/need-verify': typeof DashboardNeedVerifyRoute
  '/dashboard/not-connected': typeof DashboardNotConnectedRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/saved-strategies': typeof DashboardSavedStrategiesRoute
  '/dashboard/strategies': typeof DashboardStrategiesRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/pcxfx/login': typeof PcxfxLoginRoute
  '/pcxfx/registration': typeof PcxfxRegistrationRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/strategies/$username': typeof StrategiesUsernameRoute
  '/unfollow/confirmation': typeof UnfollowConfirmationRoute
  '/unfollow/failed': typeof UnfollowFailedRoute
  '/unfollow/information': typeof UnfollowInformationRoute
  '/unfollow/loading': typeof UnfollowLoadingRoute
  '/unfollow/success': typeof UnfollowSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/strategies/$strategyId/$step': typeof StrategiesStrategyIdStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/followed': typeof DashboardFollowedRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/need-following': typeof DashboardNeedFollowingRoute
  '/dashboard/need-verify': typeof DashboardNeedVerifyRoute
  '/dashboard/not-connected': typeof DashboardNotConnectedRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/saved-strategies': typeof DashboardSavedStrategiesRoute
  '/dashboard/strategies': typeof DashboardStrategiesRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/pcxfx/login': typeof PcxfxLoginRoute
  '/pcxfx/registration': typeof PcxfxRegistrationRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/strategies/$username': typeof StrategiesUsernameRoute
  '/unfollow/confirmation': typeof UnfollowConfirmationRoute
  '/unfollow/failed': typeof UnfollowFailedRoute
  '/unfollow/information': typeof UnfollowInformationRoute
  '/unfollow/loading': typeof UnfollowLoadingRoute
  '/unfollow/success': typeof UnfollowSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/strategies': typeof StrategiesIndexRoute
  '/strategies/$strategyId/$step': typeof StrategiesStrategyIdStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/followed': typeof DashboardFollowedRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/need-following': typeof DashboardNeedFollowingRoute
  '/dashboard/need-verify': typeof DashboardNeedVerifyRoute
  '/dashboard/not-connected': typeof DashboardNotConnectedRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/saved-strategies': typeof DashboardSavedStrategiesRoute
  '/dashboard/strategies': typeof DashboardStrategiesRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/pcxfx/login': typeof PcxfxLoginRoute
  '/pcxfx/registration': typeof PcxfxRegistrationRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/strategies/$username': typeof StrategiesUsernameRoute
  '/unfollow/confirmation': typeof UnfollowConfirmationRoute
  '/unfollow/failed': typeof UnfollowFailedRoute
  '/unfollow/information': typeof UnfollowInformationRoute
  '/unfollow/loading': typeof UnfollowLoadingRoute
  '/unfollow/success': typeof UnfollowSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/strategies/$strategyId/$step': typeof StrategiesStrategyIdStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/dashboard/account'
    | '/dashboard/followed'
    | '/dashboard/learn'
    | '/dashboard/need-following'
    | '/dashboard/need-verify'
    | '/dashboard/not-connected'
    | '/dashboard/portfolio'
    | '/dashboard/saved-strategies'
    | '/dashboard/strategies'
    | '/onboarding/$step'
    | '/pcxfx/login'
    | '/pcxfx/registration'
    | '/sitemap/xml'
    | '/strategies/$username'
    | '/unfollow/confirmation'
    | '/unfollow/failed'
    | '/unfollow/information'
    | '/unfollow/loading'
    | '/unfollow/success'
    | '/dashboard/'
    | '/strategies/'
    | '/strategies/$strategyId/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/dashboard/account'
    | '/dashboard/followed'
    | '/dashboard/learn'
    | '/dashboard/need-following'
    | '/dashboard/need-verify'
    | '/dashboard/not-connected'
    | '/dashboard/portfolio'
    | '/dashboard/saved-strategies'
    | '/dashboard/strategies'
    | '/onboarding/$step'
    | '/pcxfx/login'
    | '/pcxfx/registration'
    | '/sitemap/xml'
    | '/strategies/$username'
    | '/unfollow/confirmation'
    | '/unfollow/failed'
    | '/unfollow/information'
    | '/unfollow/loading'
    | '/unfollow/success'
    | '/dashboard'
    | '/strategies'
    | '/strategies/$strategyId/$step'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/dashboard/account'
    | '/dashboard/followed'
    | '/dashboard/learn'
    | '/dashboard/need-following'
    | '/dashboard/need-verify'
    | '/dashboard/not-connected'
    | '/dashboard/portfolio'
    | '/dashboard/saved-strategies'
    | '/dashboard/strategies'
    | '/onboarding/$step'
    | '/pcxfx/login'
    | '/pcxfx/registration'
    | '/sitemap/xml'
    | '/strategies/$username'
    | '/unfollow/confirmation'
    | '/unfollow/failed'
    | '/unfollow/information'
    | '/unfollow/loading'
    | '/unfollow/success'
    | '/dashboard/'
    | '/strategies/'
    | '/strategies/$strategyId/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapRoute: typeof SitemapRouteWithChildren
  OnboardingStepRoute: typeof OnboardingStepRoute
  PcxfxLoginRoute: typeof PcxfxLoginRoute
  PcxfxRegistrationRoute: typeof PcxfxRegistrationRoute
  StrategiesUsernameRoute: typeof StrategiesUsernameRoute
  UnfollowConfirmationRoute: typeof UnfollowConfirmationRoute
  UnfollowFailedRoute: typeof UnfollowFailedRoute
  UnfollowInformationRoute: typeof UnfollowInformationRoute
  UnfollowLoadingRoute: typeof UnfollowLoadingRoute
  UnfollowSuccessRoute: typeof UnfollowSuccessRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
  StrategiesStrategyIdStepRoute: typeof StrategiesStrategyIdStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/unfollow/success': {
      id: '/unfollow/success'
      path: '/unfollow/success'
      fullPath: '/unfollow/success'
      preLoaderRoute: typeof UnfollowSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unfollow/loading': {
      id: '/unfollow/loading'
      path: '/unfollow/loading'
      fullPath: '/unfollow/loading'
      preLoaderRoute: typeof UnfollowLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unfollow/information': {
      id: '/unfollow/information'
      path: '/unfollow/information'
      fullPath: '/unfollow/information'
      preLoaderRoute: typeof UnfollowInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unfollow/failed': {
      id: '/unfollow/failed'
      path: '/unfollow/failed'
      fullPath: '/unfollow/failed'
      preLoaderRoute: typeof UnfollowFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unfollow/confirmation': {
      id: '/unfollow/confirmation'
      path: '/unfollow/confirmation'
      fullPath: '/unfollow/confirmation'
      preLoaderRoute: typeof UnfollowConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/$username': {
      id: '/strategies/$username'
      path: '/strategies/$username'
      fullPath: '/strategies/$username'
      preLoaderRoute: typeof StrategiesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof SitemapRoute
    }
    '/pcxfx/registration': {
      id: '/pcxfx/registration'
      path: '/pcxfx/registration'
      fullPath: '/pcxfx/registration'
      preLoaderRoute: typeof PcxfxRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcxfx/login': {
      id: '/pcxfx/login'
      path: '/pcxfx/login'
      fullPath: '/pcxfx/login'
      preLoaderRoute: typeof PcxfxLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/strategies': {
      id: '/dashboard/strategies'
      path: '/strategies'
      fullPath: '/dashboard/strategies'
      preLoaderRoute: typeof DashboardStrategiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved-strategies': {
      id: '/dashboard/saved-strategies'
      path: '/saved-strategies'
      fullPath: '/dashboard/saved-strategies'
      preLoaderRoute: typeof DashboardSavedStrategiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/not-connected': {
      id: '/dashboard/not-connected'
      path: '/not-connected'
      fullPath: '/dashboard/not-connected'
      preLoaderRoute: typeof DashboardNotConnectedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/need-verify': {
      id: '/dashboard/need-verify'
      path: '/need-verify'
      fullPath: '/dashboard/need-verify'
      preLoaderRoute: typeof DashboardNeedVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/need-following': {
      id: '/dashboard/need-following'
      path: '/need-following'
      fullPath: '/dashboard/need-following'
      preLoaderRoute: typeof DashboardNeedFollowingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/learn': {
      id: '/dashboard/learn'
      path: '/learn'
      fullPath: '/dashboard/learn'
      preLoaderRoute: typeof DashboardLearnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/followed': {
      id: '/dashboard/followed'
      path: '/followed'
      fullPath: '/dashboard/followed'
      preLoaderRoute: typeof DashboardFollowedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/strategies/$strategyId/$step': {
      id: '/strategies/$strategyId/$step'
      path: '/strategies/$strategyId/$step'
      fullPath: '/strategies/$strategyId/$step'
      preLoaderRoute: typeof StrategiesStrategyIdStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardFollowedRoute: typeof DashboardFollowedRoute
  DashboardLearnRoute: typeof DashboardLearnRoute
  DashboardNeedFollowingRoute: typeof DashboardNeedFollowingRoute
  DashboardNeedVerifyRoute: typeof DashboardNeedVerifyRoute
  DashboardNotConnectedRoute: typeof DashboardNotConnectedRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardSavedStrategiesRoute: typeof DashboardSavedStrategiesRoute
  DashboardStrategiesRoute: typeof DashboardStrategiesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardFollowedRoute: DashboardFollowedRoute,
  DashboardLearnRoute: DashboardLearnRoute,
  DashboardNeedFollowingRoute: DashboardNeedFollowingRoute,
  DashboardNeedVerifyRoute: DashboardNeedVerifyRoute,
  DashboardNotConnectedRoute: DashboardNotConnectedRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardSavedStrategiesRoute: DashboardSavedStrategiesRoute,
  DashboardStrategiesRoute: DashboardStrategiesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SitemapRouteChildren {
  SitemapXmlRoute: typeof SitemapXmlRoute
}

const SitemapRouteChildren: SitemapRouteChildren = {
  SitemapXmlRoute: SitemapXmlRoute,
}

const SitemapRouteWithChildren =
  SitemapRoute._addFileChildren(SitemapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapRoute: SitemapRouteWithChildren,
  OnboardingStepRoute: OnboardingStepRoute,
  PcxfxLoginRoute: PcxfxLoginRoute,
  PcxfxRegistrationRoute: PcxfxRegistrationRoute,
  StrategiesUsernameRoute: StrategiesUsernameRoute,
  UnfollowConfirmationRoute: UnfollowConfirmationRoute,
  UnfollowFailedRoute: UnfollowFailedRoute,
  UnfollowInformationRoute: UnfollowInformationRoute,
  UnfollowLoadingRoute: UnfollowLoadingRoute,
  UnfollowSuccessRoute: UnfollowSuccessRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
  StrategiesStrategyIdStepRoute: StrategiesStrategyIdStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
